// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSWalYgbtbNAyT6JdUMbXY4SyltNe3aWM',
    appId: '1:673314892396:web:a1dce0cd1e20403ca38649',
    messagingSenderId: '673314892396',
    projectId: 'esl-ecommerce',
    authDomain: 'esl-ecommerce.firebaseapp.com',
    storageBucket: 'esl-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCag_U-7N6Uu-WUMsiv_bM-g5sbjB2W0IA',
    appId: '1:673314892396:android:a7aa80d3192abf00a38649',
    messagingSenderId: '673314892396',
    projectId: 'esl-ecommerce',
    storageBucket: 'esl-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBneGhkPSgc_E4YbC4rJnEQ79zbVsc22mg',
    appId: '1:673314892396:ios:b037b391fd8154eea38649',
    messagingSenderId: '673314892396',
    projectId: 'esl-ecommerce',
    storageBucket: 'esl-ecommerce.appspot.com',
    iosClientId: '673314892396-ju5faup08cqdoafp0h4t1refh6oeup1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.eslEcommerce',
  );
}
